-- =============================================================================
-- Tandem Database Schema (PostgreSQL 15+ / Neon)
-- Run with: php scripts/db.php migrate
-- =============================================================================

-- Case-insensitive text type for emails (matches MySQL's default collation behaviour)
CREATE EXTENSION IF NOT EXISTS citext;

DROP TABLE IF EXISTS notifications, reviews, messages, project_requests,
                     service_images, services, categories, users CASCADE;

-- Keeps updated_at current on every UPDATE (replaces MySQL's ON UPDATE CURRENT_TIMESTAMP)
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- -----------------------------------------------------------------------------
-- 1. USERS
-- Stores account information for clients, freelancers, and admins.
-- -----------------------------------------------------------------------------
CREATE TABLE users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR(100) NOT NULL,
  email         CITEXT NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role          VARCHAR(20) NOT NULL DEFAULT 'client',
  avatar_url    VARCHAR(512),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT uk_users_email UNIQUE (email),
  CONSTRAINT chk_users_role CHECK (role IN ('client', 'freelancer', 'admin'))
);
CREATE INDEX idx_users_role ON users (role);
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- -----------------------------------------------------------------------------
-- 2. CATEGORIES
-- Taxonomy for grouping marketplace services.
-- -----------------------------------------------------------------------------
CREATE TABLE categories (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(100) NOT NULL,
  slug       VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT uk_categories_slug UNIQUE (slug)
);

-- -----------------------------------------------------------------------------
-- 3. SERVICES
-- Gig or service listings posted by freelancers.
-- Deleting a freelancer cascades to their services; a category in use cannot be deleted.
-- -----------------------------------------------------------------------------
CREATE TABLE services (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  freelancer_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  category_id   BIGINT NOT NULL REFERENCES categories (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  title         VARCHAR(255) NOT NULL,
  description   TEXT NOT NULL,
  price         NUMERIC(10, 2) NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_services_freelancer_id ON services (freelancer_id);
CREATE INDEX idx_services_category_id   ON services (category_id);
CREATE INDEX idx_services_price         ON services (price);
CREATE TRIGGER trg_services_updated_at BEFORE UPDATE ON services
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- -----------------------------------------------------------------------------
-- 4. SERVICE_IMAGES
-- Gallery images associated with a service listing.
-- -----------------------------------------------------------------------------
CREATE TABLE service_images (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id BIGINT NOT NULL REFERENCES services (id) ON DELETE CASCADE ON UPDATE CASCADE,
  image_path VARCHAR(512) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_service_images_service_id ON service_images (service_id);

-- -----------------------------------------------------------------------------
-- 5. PROJECT_REQUESTS
-- Client inquiries and project requests tied to a service.
-- If a service is deleted, the request history is preserved (service_id → NULL).
-- -----------------------------------------------------------------------------
CREATE TABLE project_requests (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id  BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  service_id BIGINT REFERENCES services (id) ON DELETE SET NULL ON UPDATE CASCADE,
  message    TEXT NOT NULL,
  status     VARCHAR(20) NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT chk_project_requests_status CHECK (
    status IN ('pending', 'accepted', 'rejected', 'in_progress', 'completed', 'cancelled')
  )
);
CREATE INDEX idx_project_requests_client_id  ON project_requests (client_id);
CREATE INDEX idx_project_requests_service_id ON project_requests (service_id);
CREATE INDEX idx_project_requests_status     ON project_requests (status);
CREATE TRIGGER trg_project_requests_updated_at BEFORE UPDATE ON project_requests
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- -----------------------------------------------------------------------------
-- 6. MESSAGES
-- Direct messages between users, optionally tied to a project request.
-- -----------------------------------------------------------------------------
CREATE TABLE messages (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id          BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  receiver_id        BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  project_request_id BIGINT REFERENCES project_requests (id) ON DELETE SET NULL ON UPDATE CASCADE,
  body               TEXT NOT NULL,
  is_read            BOOLEAN NOT NULL DEFAULT FALSE,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_messages_sender_id          ON messages (sender_id);
CREATE INDEX idx_messages_receiver_id        ON messages (receiver_id);
CREATE INDEX idx_messages_project_request_id ON messages (project_request_id);
CREATE INDEX idx_messages_unread             ON messages (receiver_id, is_read);

-- -----------------------------------------------------------------------------
-- 7. REVIEWS
-- Feedback and 1-5 star ratings given by clients for completed project requests.
-- -----------------------------------------------------------------------------
CREATE TABLE reviews (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_request_id BIGINT NOT NULL REFERENCES project_requests (id) ON DELETE CASCADE ON UPDATE CASCADE,
  client_id          BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  freelancer_id      BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  rating             SMALLINT NOT NULL,
  comment            TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT uk_reviews_project_request UNIQUE (project_request_id),
  CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 5)
);
CREATE INDEX idx_reviews_client_id     ON reviews (client_id);
CREATE INDEX idx_reviews_freelancer_id ON reviews (freelancer_id);
CREATE INDEX idx_reviews_rating        ON reviews (rating);

-- -----------------------------------------------------------------------------
-- 8. NOTIFICATIONS
-- In-app notifications sent to users with structured JSON payloads.
-- -----------------------------------------------------------------------------
CREATE TABLE notifications (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  type       VARCHAR(50) NOT NULL,
  payload    JSONB NOT NULL,
  is_read    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_notifications_user_unread ON notifications (user_id, is_read, created_at);
